version: "3.9"

services:
    app:
        container_name: pkmn-calculator
        image: pkmn-calculator
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
